import { Fragment } from 'react';
import { Document, Page, View, Text, Image, Link, StyleSheet, Font, pdf } from '@react-pdf/renderer';
import type { Language, NutritionEstimate } from '../types';
import { ingredientLines } from '../utils/ingredients';
import { BOOKLET_THEMES, type BookletTheme, type BookletThemeId } from './bookletThemes';

// Magazine-style recipe booklet: a cover with a masthead and hero photo, a
// contents page, an optional editor's note, one recipe feature per page
// (hero photo, pull-quote, ingredients sidebar, numbered method) and a back
// cover with a dedication. Imported lazily (see BookletModal.tsx) — this
// module and @react-pdf/renderer are only fetched when someone actually
// generates a booklet, so they never bloat the main app bundle.

export interface BookletItem {
  id: string;
  dishName: string;
  photoSrc?: string; // remote https URL (published posts) or a data: URI (drafts, read from IndexedDB)
  reflection: string;
  ingredients?: string;
  recipe?: string;
  spiritTags: string[];
  spiritTagLabels: Record<string, string>;
  categoryLabel?: string;
  nutrition?: NutritionEstimate | null;
}

export interface BookletCopy {
  ingredientsHeading: string;
  recipeHeading: string;
  contentsHeading: string;
  editorNoteHeading: string;
  questionsHeading: string;
  recipeCount: (n: number) => string;
  nutritionHeading: string;
  // Labels for the nutrition strip; calories is the unit ("kcal" / "大卡").
  nutritionLabels: { calories: string; protein: string; carbs: string; fat: string; fiber: string };
  madeWith: string;
  tagline: string;
}

export interface BookletOptions {
  title: string;
  dedication?: string;
  theme: BookletThemeId;
  editorNote?: { title: string; body: string; questions: string[] };
  language: Language;
  copy: BookletCopy;
  // 'featured' = one big photo plus a strip of smaller "also inside" photos
  // (default); 'single' = just the one featured dish.
  coverStyle?: 'single' | 'featured';
  // Recipe page layout: 'classic' (editorial, default) or 'playful' (rounded pills, tilted stickers).
  layoutStyle?: 'classic' | 'playful';
  featuredId?: string; // the dish for the cover's big photo (default: first with a photo)
  alsoInside?: string; // label above the thumbnail strip
  logoSrc?: string; // the Nouriva mark, shown on the cover and back cover
  appUrl?: string;  // link to the app, printed (and clickable) on the back cover
}

// CJK glyphs aren't in react-pdf's built-in fonts, so a booklet in Chinese
// would render as blank boxes without a registered font that actually has
// them. Only load these matching the booklet generator's own UI language —
// English stays on the zero-download built-in fonts. A booklet mixing
// languages the UI language doesn't cover is a known, accepted gap (Chinese
// scripts cover each other, see resolveFonts; English text in a Chinese UI is
// fine, Chinese text in an English-UI booklet is not).
//
// Fontsource splits CJK fonts into many unicode-range files, and the main
// "chinese-*" file lacks the full-width punctuation (，！？；：（）), so the
// few small files that hold those are registered as fallback families.
//
// The files are served from our own /fonts as UNCOMPRESSED .ttf (generated by
// scripts/build-fonts.mjs). Fontsource only ships zlib-compressed .woff, and
// react-pdf decompresses those in pure JavaScript: about 13 s per Chinese
// booklet on every generation, versus ~0.1 s for plain TTF.
let fontBase = '/fonts';
// Node-side render checks have no origin to resolve '/fonts' against.
export function setBookletFontBase(base: string) { fontBase = base; }
// `punctPkg` names the package the punctuation fallbacks come from when it isn't
// the face's own (noto-sans-tc's punctuation file is one fontkit can't parse).
interface CjkFace { pkg: string; main: string; punct: number[]; punctPkg?: string }
const CJK_FONTS: Partial<Record<Language, { serif: CjkFace; sans: CjkFace }>> = {
  'zh-Hans': {
    serif: { pkg: 'noto-serif-sc', main: 'chinese-simplified', punct: [119, 118, 117, 115] },
    sans: { pkg: 'noto-sans-sc', main: 'chinese-simplified', punct: [119, 118, 117, 115] },
  },
  'zh-Hant': {
    serif: { pkg: 'noto-serif-tc', main: 'chinese-traditional', punct: [122, 123, 119] },
    sans: { pkg: 'noto-sans-tc', main: 'chinese-traditional', punct: [122, 123, 119], punctPkg: 'noto-serif-tc' },
  },
};

interface Fonts {
  serif: string | string[];
  serifBold: string | string[];
  serifItalic: string | string[];
  sans: string | string[];
  sansBold: string | string[];
  isCjk: boolean;
}

// react-pdf hyphenates English words mid-word by default; a magazine layout
// shouldn't. (It can't wrap CJK text without also printing a "-" at each
// break — see wrapCjk below, which does that wrapping itself.)
Font.registerHyphenationCallback(word => [word]);

const registeredFamilies = new Set<string>();

function registerFamily(family: string, pkg: string, subset: string) {
  if (registeredFamilies.has(family)) return;
  Font.register({
    family,
    fonts: [
      { src: `${fontBase}/${pkg}-${subset}-400-normal.ttf`, fontWeight: 'normal' },
      { src: `${fontBase}/${pkg}-${subset}-700-normal.ttf`, fontWeight: 'bold' },
    ],
  });
  registeredFamilies.add(family);
}

function registerFace(face: CjkFace): string[] {
  const families = [face.pkg];
  registerFamily(face.pkg, face.pkg, face.main);
  const punctPkg = face.punctPkg || face.pkg;
  face.punct.forEach(n => {
    const family = `${punctPkg}-p${n}`;
    registerFamily(family, punctPkg, String(n));
    families.push(family);
  });
  return families;
}

function resolveFonts(language: Language): Fonts {
  const cjk = CJK_FONTS[language];
  if (!cjk) return { serif: 'Times-Roman', serifBold: 'Times-Bold', serifItalic: 'Times-Italic', sans: 'Helvetica', sansBold: 'Helvetica-Bold', isCjk: false };
  // One CJK family for every role: each face is ~2 MB per weight to download
  // and parse in the browser, and loading both a serif and a sans family made
  // Chinese booklets look frozen for a long time on the main thread.
  const serif = registerFace(cjk.serif);
  // Recipes are written in either script whatever the UI language is (a
  // Traditional UI showing a post written in Simplified, and vice versa). Each
  // script's font lacks characters the other uses (烧 悦 觉 / 燒 悅 覺 ...) and
  // react-pdf draws those as garbage glyphs, so the other script's main font
  // goes last in the fallback chain. Loaded on demand and cheap to parse (TTF).
  const other = CJK_FONTS[language === 'zh-Hant' ? 'zh-Hans' : 'zh-Hant']!.serif;
  registerFamily(other.pkg, other.pkg, other.main);
  serif.push(other.pkg);
  const sans = serif;
  // Chinese typography doesn't use italics, and only normal + bold faces are
  // registered — so "italic" roles fall back to the regular serif face.
  return { serif, serifBold: serif, serifItalic: serif, sans, sansBold: sans, isCjk: true };
}

// react-pdf breaks long CJK runs at a "hyphenation point", which prints a
// stray "-" at the end of the line. So for Chinese we wrap the text ourselves
// with explicit newlines, from an estimated advance width per character
// (full-width glyphs = 1em, Latin/digits about half). `NO_LINE_START` keeps
// closing punctuation from starting a line (it hangs at the end instead).
const CJK_CHAR = /[⺀-鿿＀-￯　-〿]/;
const NO_LINE_START = /[，。、；：！？）」』》〉】〕…—,.;:!?)\]]/;

function wrapCjk(text: string, width: number, size: number): string {
  const limit = width * 0.95;
  return text
    .split('\n')
    .map(para => {
      const lines: string[] = [];
      let cur = '';
      let w = 0;
      for (const ch of Array.from(para)) {
        const cw = (CJK_CHAR.test(ch) ? 1 : /\s/.test(ch) ? 0.3 : 0.56) * size;
        if (w + cw > limit && cur && !NO_LINE_START.test(ch)) {
          lines.push(cur);
          cur = '';
          w = 0;
        }
        cur += ch;
        w += cw;
      }
      lines.push(cur);
      return lines.join('\n');
    })
    .join('\n');
}

// Method text: one step per line if the author wrote lines, otherwise split
// into sentences, so a paragraph of prose still reads as numbered steps.
function toSteps(text: string): string[] {
  const lines = text.split(/\r?\n/).map(l => l.replace(/^\s*(?:\d+[.)、]|[-•*])\s*/, '').trim()).filter(Boolean);
  if (lines.length > 1) return lines;
  const sentences = (lines[0] || '').match(/[^.!?。！？]+[.!?。！？]?/g)?.map(s => s.trim()).filter(Boolean) || [];
  return sentences.length > 1 ? sentences : lines;
}

const toIngredients = ingredientLines;

function issueLine(language: Language): string {
  const locale = language === 'zh-Hant' ? 'zh-TW' : language === 'zh-Hans' ? 'zh-CN' : 'en-GB';
  return new Date().toLocaleDateString(locale, { month: 'long', year: 'numeric' });
}

function buildStyles(th: BookletTheme, f: Fonts, k = 1) {
  const track = f.isCjk ? 1.5 : 2.4;
  return StyleSheet.create({
    // --- shared
    page: { backgroundColor: th.paper, color: th.ink, fontFamily: f.sans, fontSize: 10.5 },
    label: { fontFamily: f.sans, fontSize: 8, letterSpacing: track, textTransform: 'uppercase', color: th.strong },
    pageFooter: { position: 'absolute', bottom: 22, left: 44, right: 44, flexDirection: 'row', justifyContent: 'space-between', fontSize: 7.5, color: th.muted, letterSpacing: 1 },

    // --- cover
    coverPage: { backgroundColor: th.deep, color: th.paper, padding: 0 },
    coverTop: { paddingTop: 32, paddingHorizontal: 44, alignItems: 'center' },
    coverLogo: { width: 46, height: 46, marginBottom: 12 },
    coverIssue: { fontFamily: f.sans, fontSize: 8.5, letterSpacing: track + 0.6, textTransform: 'uppercase', color: th.accent },
    coverTitle: { fontFamily: f.serifBold, color: th.paper, textAlign: 'center', marginTop: 10 },
    coverTagline: { fontFamily: f.sans, fontSize: 8, letterSpacing: track, textTransform: 'uppercase', color: th.accent, marginTop: 8, textAlign: 'center' },
    coverFrame: { marginTop: 24, marginHorizontal: 44, height: 470, borderWidth: 1.5, borderColor: th.accent, padding: 6 },
    coverPhoto: { width: '100%', height: '100%', objectFit: 'cover' },
    coverAlsoLabel: { fontFamily: f.sans, fontSize: 7.5, letterSpacing: track, textTransform: 'uppercase', color: th.accent, marginTop: 8, marginBottom: 4 },
    coverThumbRow: { flexDirection: 'row' },
    coverThumb: { flexGrow: 1, flexBasis: 0 },
    coverThumbImg: { width: '100%', height: 70, objectFit: 'cover' },
    coverThumbName: { fontFamily: f.serif, fontSize: 8.5, color: th.paper, marginTop: 3, maxLines: 1 },
    coverBlock: { width: '100%', height: '100%', backgroundColor: th.accent, alignItems: 'center', justifyContent: 'center' },
    coverBlockLetter: { fontFamily: f.serifBold, fontSize: 150, color: th.deep },
    coverBottom: { marginTop: 26, paddingHorizontal: 44 },
    coverLine: { fontFamily: f.serifItalic, fontSize: 24, lineHeight: 1.25, color: th.paper },
    coverCount: { fontFamily: f.sans, fontSize: 8.5, letterSpacing: track, textTransform: 'uppercase', color: th.accent, marginTop: 10 },

    // --- contents & editor's note
    inner: { paddingTop: 54, paddingHorizontal: 54, paddingBottom: 54 },
    heading: { fontFamily: f.serifBold, fontSize: 32, lineHeight: 1.15, color: th.ink, marginTop: 6, marginBottom: 20 },
    rule: { height: 1, backgroundColor: th.strong, opacity: 0.5, marginBottom: 6 },
    tocRow: { flexDirection: 'row', alignItems: 'flex-end', paddingVertical: 9, borderBottomWidth: 0.6, borderBottomColor: '#D9CDB0' },
    tocNum: { fontFamily: f.serifBold, fontSize: 17, color: th.strong, width: 38 },
    tocTitle: { fontFamily: f.serif, fontSize: 15, flex: 1, color: th.ink },
    tocMeta: { fontFamily: f.sans, fontSize: 8, letterSpacing: 1.2, textTransform: 'uppercase', color: th.muted, marginLeft: 8, textAlign: 'right', maxWidth: 150 },
    noteBody: { fontFamily: f.serif, fontSize: 12.5, lineHeight: 1.65, color: th.ink, marginBottom: 12 },
    noteQuestions: { backgroundColor: th.tint, padding: 16, marginTop: 14 },
    noteQuestion: { fontFamily: f.serifItalic, fontSize: 12, lineHeight: 1.55, color: th.ink, marginBottom: 6 },

    // --- recipe feature
    heroImage: { width: '100%', height: 360, objectFit: 'cover' },
    heroBlock: { width: '100%', height: 260, backgroundColor: th.deep, alignItems: 'center', justifyContent: 'center' },
    heroLetter: { fontFamily: f.serifBold, fontSize: 110, color: th.accent },
    kicker: { flexDirection: 'row', marginBottom: 6 },
    recipeTitle: { fontFamily: f.serifBold, fontSize: 34 * k, lineHeight: 1.2, color: th.ink },
    meta: { fontFamily: f.sans, fontSize: 8.5, letterSpacing: 1.4, textTransform: 'uppercase', color: th.strong, marginTop: 10 },
    pullQuote: { fontFamily: f.serifItalic, fontSize: 15 * k, lineHeight: 1.5, color: th.ink, marginTop: 16, marginBottom: 4, paddingLeft: 14, borderLeftWidth: 2.5, borderLeftColor: th.strong },
    columns: { flexDirection: 'row', marginTop: 20 },
    sidebar: { width: '36%', backgroundColor: th.tint, padding: 14, marginRight: 20 },
    sideHeading: { fontFamily: f.sans, fontSize: 8, letterSpacing: track, textTransform: 'uppercase', color: th.strong, marginBottom: 8 },
    ingredient: { fontFamily: f.sans, fontSize: 10.5 * k, lineHeight: 1.5, marginBottom: 4, color: th.ink },
    main: { flex: 1 },
    stepRow: { flexDirection: 'row', marginBottom: 8 },
    stepNum: { fontFamily: f.serifBold, fontSize: 15 * k, color: th.strong, width: 24 },
    stepText: { fontFamily: f.sans, fontSize: 11 * k, lineHeight: 1.55, flex: 1, color: th.ink },
    nutrition: { marginTop: 14, paddingTop: 8, borderTopWidth: 0.6, borderTopColor: th.strong },
    nutritionLine: { fontFamily: f.sans, fontSize: 9 * k, color: th.ink, lineHeight: 1.4 },
    nutritionLabel: { fontFamily: f.sans, fontSize: 7.5, letterSpacing: 1.6, textTransform: 'uppercase', color: th.strong, marginBottom: 3 },

    // --- back cover
    backPage: { backgroundColor: th.deep, color: th.paper, justifyContent: 'center', alignItems: 'center', padding: 70 },
    dedication: { fontFamily: f.serifItalic, fontSize: 20, lineHeight: 1.5, textAlign: 'center', color: th.paper },
    backRule: { width: 60, height: 1.5, backgroundColor: th.accent, marginVertical: 26 },
    backLogo: { width: 64, height: 64, marginBottom: 18 },
    backLink: { fontFamily: f.sans, fontSize: 10, letterSpacing: 1.2, color: th.paper, textDecoration: 'none', marginTop: 10, textAlign: 'center' },
    backMark: { fontFamily: f.sans, fontSize: 8.5, letterSpacing: track, textTransform: 'uppercase', color: th.accent, textAlign: 'center' },
  });
}

// One recipe = one page, whatever its length. For each recipe the layout is
// chosen from estimated text heights (average glyph advances, deliberately a
// little pessimistic):
//   1. "sidebar": ingredients in a narrow column beside the method (the
//      default look) — used while it leaves room for a good photo;
//   2. "wide": ingredients in a full-width box with TWO columns, method full
//      width below — much shorter for long ingredient lists;
//   3. type shrinks a little (down to 85%) before the photo does, and the
//      photo only shrinks to ~120pt;
//   4. if it STILL can't fit, the method moves to its own second page
//      (titled, clean) rather than spilling over mid-sentence.
const PAGE_H = 842;
const FOOTER_RESERVE = 56;
const PHOTO_IDEAL = 200;
const PHOTO_MIN = 105;

type Layout = 'sidebar' | 'wide';
interface RecipePlan { layout: Layout; k: number; heroH: number; twoPage: boolean; alt: boolean }

function estLines(text: string, width: number, size: number, cjk: boolean, charW = 0.55): number {
  const perLine = Math.max(1, Math.floor(width / (size * (cjk ? 1 : charW))));
  return text.split('\n').reduce((n, para) => n + Math.max(1, Math.ceil(para.length / perLine)), 0);
}

// CJK fonts (Noto) draw taller line boxes than Latin ones at the same lineHeight, measured ~1.3x.
const LH = (cjk: boolean) => (cjk ? 1.3 : 1);
const ingHeight = (l: string, width: number, k: number, cjk: boolean) => estLines(l, width, 10.5 * k, cjk) * 10.5 * k * 1.5 * LH(cjk) + 4;
const stepHeight = (l: string, width: number, k: number, cjk: boolean) => estLines(l, width, 11 * k, cjk) * 11 * k * 1.55 * LH(cjk) + 8;

// Split an ingredient list into two columns of near-equal height.
function splitColumns(ingredients: string[], width: number, k: number, cjk: boolean): [string[], string[]] {
  const heights = ingredients.map(l => ingHeight(l, width, k, cjk));
  const total = heights.reduce((a, b) => a + b, 0);
  let acc = 0;
  let cut = ingredients.length;
  for (let i = 0; i < heights.length; i++) {
    if (acc + heights[i] / 2 >= total / 2) { cut = i; break; }
    acc += heights[i];
  }
  cut = Math.min(Math.max(cut, 1), Math.max(1, ingredients.length - 1));
  return [ingredients.slice(0, cut), ingredients.slice(cut)];
}

function headerHeight(item: BookletItem, k: number, cjk: boolean, withQuote: boolean): number {
  const title = estLines(item.dishName || ' ', 487, 34 * k, cjk) * 34 * k * 1.2 * LH(cjk);
  const tags = item.spiritTags.length > 0 ? 22 : 0;
  const quote = withQuote && item.reflection ? estLines(item.reflection, 468, 15 * k, cjk) * 15 * k * 1.5 * LH(cjk) + 20 : 0;
  return 14 + title + tags + quote;
}

function methodHeight(steps: string[], width: number, k: number, cjk: boolean): number {
  return steps.length ? 26 + steps.reduce((h, l) => h + stepHeight(l, width, k, cjk), 0) : 0;
}

function wideIngredientsHeight(ingredients: string[], k: number, cjk: boolean): number {
  if (!ingredients.length) return 0;
  const [a, b] = splitColumns(ingredients, 222, k, cjk);
  const col = (c: string[]) => c.reduce((h, l) => h + ingHeight(l, 222, k, cjk), 0);
  return 28 + 18 + Math.max(col(a), col(b));
}

function planRecipe(item: BookletItem, altPreferred: boolean, cjk: boolean, nutritionLines: number): RecipePlan {
  const steps = item.recipe ? toSteps(item.recipe) : [];
  const ingredients = item.ingredients ? toIngredients(item.ingredients) : [];
  const nutritionH = (k: number) => (nutritionLines ? 22 + nutritionLines * 9 * k * 1.4 * LH(cjk) : 0);

  // Photo height left for a layout at type scale k (title-above-photo
  // arrangement costs ~42pt more than photo-on-top).
  const heightFor = (k: number, layout: Layout, alt: boolean) => {
    const top = alt ? 46 + 18 : 22;
    const head = headerHeight(item, k, cjk, true);
    let body: number;
    if (layout === 'sidebar') {
      const side = ingredients.length ? 40 + ingredients.reduce((h, l) => h + ingHeight(l, 147, k, cjk), 0) : 0;
      const main = methodHeight(steps, 268, k, cjk);
      body = side || main ? 20 + Math.max(side, main) : 0;
    } else {
      const ing = wideIngredientsHeight(ingredients, k, cjk);
      const main = methodHeight(steps, 463, k, cjk);
      body = ing || main ? 20 + ing + (ing && main ? 14 : 0) + main : 0;
    }
    return Math.min(360, PAGE_H - FOOTER_RESERVE - top - (head + body + nutritionH(k)));
  };

  const ks = [1, 0.92, 0.85, 0.8];
  const layouts: Layout[] = ['sidebar', 'wide'];
  // Try the alternating arrangement first, then photo-on-top (more room).
  for (const alt of altPreferred ? [true, false] : [false]) {
    // Pass 1: a generous photo. Pass 2: a small one, rather than a second page.
    for (const minHero of [PHOTO_IDEAL, PHOTO_MIN]) {
      for (const k of ks) {
        for (const layout of layouts) {
          const heroH = heightFor(k, layout, alt);
          if (heroH >= minHero) return { layout, k, heroH, twoPage: false, alt };
        }
      }
    }
  }
  // Two pages: page 1 = photo, title, quote, ingredients (wide); page 2 = method.
  const top = altPreferred ? 64 : 22;
  const first = headerHeight(item, 1, cjk, true) + 20 + wideIngredientsHeight(ingredients, 1, cjk);
  const heroH = Math.max(PHOTO_MIN, Math.min(300, PAGE_H - FOOTER_RESERVE - top - first));
  return { layout: 'wide', k: 1, heroH, twoPage: steps.length > 0, alt: altPreferred };
}

function nutritionParts(n: NutritionEstimate | null | undefined, labels: BookletCopy['nutritionLabels']): string[] {
  if (!n) return [];
  const parts: string[] = [];
  if (n.calories !== undefined) parts.push(`${Math.round(n.calories)} ${labels.calories}`);
  if (n.proteinGrams !== undefined) parts.push(`${labels.protein} ${Math.round(n.proteinGrams)} g`);
  if (n.carbsGrams !== undefined) parts.push(`${labels.carbs} ${Math.round(n.carbsGrams)} g`);
  if (n.fatGrams !== undefined) parts.push(`${labels.fat} ${Math.round(n.fatGrams)} g`);
  if (n.fiberGrams !== undefined) parts.push(`${labels.fiber} ${Math.round(n.fiberGrams)} g`);
  return parts;
}

// "Playful" recipe page: highlighted title, round photo with its timing line,
// ingredient pills, offset step bubbles and a tilted note. The type scale and
// photo size shrink until it fits one page; if it still can't, the step
// bubbles (which never split) simply continue on a second page.
const PLAY_W = 487; // A4 width 595 minus 2 x 54 margin
// Average Helvetica glyph advance in em, measured on real recipes (0.55 over-estimated and shrank the photo for no reason).
const PLAY_CHAR = 0.47;
const PLAY_NOTE_CHAR = 0.44; // the note is set in Times-Italic, which is narrower
const PLAY_PHOTO = 200;
const STICKER = 64;
const STICKER_GAP = 8;

// AI recipes open the method with a timing line ("Prep 10 min · Cook 25 min ·
// Serves 2"). The playful page shows that under the photo instead of as step 1.
// "Prep 15 min · Cook 20 min · Serves 12" -> three stickers (label + value).
function metaStickers(meta: string): { label: string; value: string }[] {
  return meta.split(/\s*[·|]\s*/).filter(Boolean).slice(0, 3).map(seg => {
    const m = seg.match(/^(\D+?)\s*(\d.*)$/);
    return m ? { label: m[1].trim(), value: m[2].trim() } : { label: '', value: seg.trim() };
  });
}

function playSteps(item: BookletItem): { meta: string; steps: string[] } {
  const all = item.recipe ? toSteps(item.recipe) : [];
  const first = all[0] || '';
  const isMeta = first.length <= 80 && /[·|]/.test(first) && /\d/.test(first);
  return isMeta ? { meta: first, steps: all.slice(1) } : { meta: '', steps: all };
}

function pillWidth(text: string, k: number, cjk: boolean): number {
  return text.length * 10.5 * k * (cjk ? 1 : PLAY_CHAR) + 22;
}

// Greedy row packing, the way flex-wrap lays the pills out.
function pillRows(lines: string[], k: number, cjk: boolean): number {
  let rows = 1;
  let x = 0;
  let extra = 0;
  for (const l of lines) {
    const full = pillWidth(l, k, cjk);
    if (full > PLAY_W) extra += estLines(l, PLAY_W - 22, 10.5 * k, cjk, PLAY_CHAR) - 1;
    const w = Math.min(full, PLAY_W);
    if (x + w > PLAY_W && x > 0) { rows++; x = 0; }
    x += w + 5;
  }
  return rows + extra;
}

// Greedy word wrap for the title (it's big, so a char-count estimate is too coarse).
function titleLines(text: string, width: number, size: number, cjk: boolean): number {
  if (cjk) return estLines(text, width, size, true);
  const em = size * 0.56;
  let lines = 1;
  let x = 0;
  for (const w of text.split(/\s+/).filter(Boolean)) {
    const ww = w.length * em;
    if (x > 0 && x + em * 0.3 + ww > width) { lines++; x = ww; } else x += (x ? em * 0.3 : 0) + ww;
  }
  return lines;
}

function planPlayful(item: BookletItem, cjk: boolean, hasNutrition: boolean, flip = false): { k: number; photo: number } {
  const { meta, steps } = playSteps(item);
  const ingredients = item.ingredients ? toIngredients(item.ingredients) : [];
  const avail = PAGE_H - 40 - FOOTER_RESERVE;
  const stickerCount = metaStickers(meta).length;
  const metaH = stickerCount ? STICKER + 16 : 0;
  const metaW = stickerCount * STICKER + (stickerCount - 1) * STICKER_GAP;
  let best = { k: 0.8, photo: 115 };
  // Every recipe gets the same photo size so the booklet looks consistent; the
  // type scale shrinks to make room. Only if it still can't fit at the smallest
  // type does the photo step down.
  for (const photo of [PLAY_PHOTO, 175, 150, 130, 115]) {
    for (const k of [1, 0.92, 0.85, 0.8]) {
      best = { k, photo };
      const titleW = PLAY_W - (photo + 14) - 10;
      const titleH = titleLines(item.dishName || ' ', titleW, 36 * k, cjk) * 36 * k * 1.2 * LH(cjk) + 6;
      const tags = item.spiritTags.length > 0 ? 26 : 0;
      const head = Math.max(photo + 14, titleH + tags + 30 + metaH);
      if (titleW < metaW) continue; // the sticker row must fit beside the photo
      const ing = ingredients.length ? 24 + pillRows(ingredients, k, cjk) * (10.5 * k * 1.3 * LH(cjk) + 17) : 0;
      const stp = steps.reduce((h, l, i) => h + estLines(l, PLAY_W - ((i + (flip ? 1 : 0)) % 2 ? 40 : 18) - 46, 11 * k, cjk, PLAY_CHAR) * 11 * k * 1.4 * LH(cjk) + 28, 0);
      const note = item.reflection ? estLines(item.reflection, PLAY_W - 34, 12 * k, cjk, PLAY_NOTE_CHAR) * 12 * k * 1.45 * LH(cjk) + 28 : 0;
      const total = head + 16 + ing + 16 + stp + 6 + note + (hasNutrition ? 36 : 0);
      if (total <= avail) return best;
    }
  }
  return best;
}

function PlayfulRecipe({ item, idx, th, f, copy, bookTitle, wrap }: {
  item: BookletItem; idx: number; th: BookletTheme; f: Fonts; copy: BookletCopy; bookTitle: string;
  wrap: (text: string, width: number, size: number) => string;
}) {
  const { meta, steps } = playSteps(item);
  const ingredients = item.ingredients ? toIngredients(item.ingredients) : [];
  const tags = item.spiritTags.map(tag => item.spiritTagLabels[tag] || tag);
  const n = item.nutrition;
  const nutrition = nutritionParts(n, copy.nutritionLabels);
  // Every other recipe is mirrored: photo on the left, the step zig-zag starts on
  // the other side and the note tilts the other way.
  const flip = idx % 2 === 1;
  const { k, photo } = planPlayful(item, f.isCjk, nutrition.length > 0, flip);
  const track = f.isCjk ? 1.2 : 1.8;
  const stickers = metaStickers(meta);
  const titleW = PLAY_W - (photo + 14) - 10;
  const tilt = ['-2deg', '2deg', '-1deg', '1.5deg'];

  return (
    <Page size="A4" style={{ backgroundColor: th.paper, color: th.ink, fontFamily: f.sans, fontSize: 10.5, paddingTop: 40, paddingHorizontal: 54, paddingBottom: FOOTER_RESERVE }}>
      <View style={{ flexDirection: flip ? 'row-reverse' : 'row', justifyContent: 'space-between' }}>
        <View style={{ width: titleW, paddingTop: 10 }}>
          <Text style={{ fontFamily: f.sans, fontSize: 9, letterSpacing: track, textTransform: 'uppercase', color: th.strong, marginBottom: 8 }}>
            {[String(idx + 1).padStart(2, '0'), item.categoryLabel].filter(Boolean).join('  ·  ')}
          </Text>
          <View style={{ alignSelf: 'flex-start', maxWidth: titleW, transform: 'rotate(-2deg)', transformOrigin: 'left top' }}>
            <Text style={{ fontFamily: f.sansBold, fontSize: 36 * k, lineHeight: 1.2, color: th.deep, backgroundColor: th.accent }}>
              {wrap(item.dishName || ' ', titleW, 36 * k)}
            </Text>
          </View>
          {tags.length > 0 && (
            <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginTop: 14 }}>
              {tags.slice(0, 3).map((tg, i) => (
                <Text key={i} style={{ fontFamily: f.sans, fontSize: 8.5, color: th.paper, backgroundColor: th.strong, paddingVertical: 3, paddingHorizontal: 9, borderRadius: 10, marginRight: 5, marginBottom: 4 }}>
                  {tg}
                </Text>
              ))}
            </View>
          )}
          {stickers.length > 0 ? (
            <View style={{ flexDirection: 'row', marginTop: 14 }}>
              {stickers.map((st, i) => (
                <View key={i} style={{
                  width: STICKER, height: STICKER, borderRadius: STICKER / 2, marginLeft: i ? STICKER_GAP : 0,
                  backgroundColor: i === 1 ? th.deep : th.strong, alignItems: 'center', justifyContent: 'center',
                  transform: `rotate(${['-8deg', '5deg', '-4deg'][i]})`,
                }}>
                  {st.label ? <Text style={{ fontFamily: f.sans, fontSize: 7.5, letterSpacing: 0.8, textTransform: 'uppercase', color: th.accent }}>{st.label}</Text> : null}
                  <Text style={{ fontFamily: f.sansBold, fontSize: st.value.length > 6 ? 10 : 13.5, lineHeight: 1.2, color: th.paper, textAlign: 'center', maxWidth: STICKER - 10 }}>{st.value}</Text>
                </View>
              ))}
            </View>
          ) : null}
        </View>
        <View style={{ width: photo + 14, alignItems: 'center' }}>
          {item.photoSrc ? (
            <Image src={item.photoSrc} style={{ width: photo, height: photo, borderRadius: photo / 2, objectFit: 'cover', borderWidth: 5, borderColor: th.accent }} />
          ) : (
            <View style={{ width: photo, height: photo, borderRadius: photo / 2, backgroundColor: th.accent, alignItems: 'center', justifyContent: 'center' }}>
              <Text style={{ fontFamily: f.sansBold, fontSize: photo * 0.5, color: th.deep }}>{(item.dishName || '·').trim().charAt(0).toUpperCase()}</Text>
            </View>
          )}
        </View>
      </View>

      {ingredients.length > 0 && (
        <View style={{ marginTop: 16 }}>
          <Text style={{ fontFamily: f.sans, fontSize: 8, letterSpacing: track, textTransform: 'uppercase', color: th.strong, marginBottom: 8 }}>{copy.ingredientsHeading}</Text>
          <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
            {ingredients.map((line, i) => (
              <Text key={i} style={{
                fontFamily: f.sans, fontSize: 10.5 * k, lineHeight: 1.3, color: th.ink,
                backgroundColor: i % 2 === 0 ? th.accent : th.tint, borderRadius: 11, paddingVertical: 5, paddingHorizontal: 11,
                marginRight: 5, marginBottom: 7, maxWidth: PLAY_W, transform: `rotate(${tilt[i % 4]})`,
              }}>
                {wrap(line, PLAY_W - 22, 10.5 * k)}
              </Text>
            ))}
          </View>
        </View>
      )}

      {steps.length > 0 && (
        <View style={{ marginTop: 16 }}>
          {steps.map((line, i) => {
            const off = (i + (flip ? 1 : 0)) % 2 ? 40 : 18;
            return (
              <View key={i} wrap={false} style={{ flexDirection: 'row', alignItems: 'center', marginLeft: off, marginBottom: 10, backgroundColor: th.tint, borderRadius: 14, paddingVertical: 9, paddingRight: 14, paddingLeft: 30 }}>
                <View style={{ position: 'absolute', left: -14, top: '50%', marginTop: -15, width: 30, height: 30, borderRadius: 15, backgroundColor: th.strong, alignItems: 'center', justifyContent: 'center' }}>
                  <Text style={{ fontFamily: f.sansBold, fontSize: 14, color: th.paper }}>{i + 1}</Text>
                </View>
                <Text style={{ fontFamily: f.sans, fontSize: 11 * k, lineHeight: 1.4, flex: 1, color: th.ink }}>{wrap(line, PLAY_W - off - 46, 11 * k)}</Text>
              </View>
            );
          })}
        </View>
      )}

      {item.reflection ? (
        <View wrap={false} style={{ marginTop: 6, backgroundColor: th.deep, borderRadius: 14, paddingVertical: 11, paddingHorizontal: 17, transform: flip ? 'rotate(1deg)' : 'rotate(-1deg)' }}>
          <Text style={{ fontFamily: f.serifItalic, fontSize: 12 * k, lineHeight: 1.45, color: th.paper }}>{wrap(item.reflection, PLAY_W - 34, 12 * k)}</Text>
        </View>
      ) : null}
      {nutrition.length > 0 && (
        <View wrap={false} style={{ flexDirection: 'row', flexWrap: 'wrap', marginTop: 14 }}>
          {nutrition.map((p, i) => (
            <Text key={i} style={{ fontFamily: f.sans, fontSize: 9, color: th.strong, borderWidth: 1, borderColor: th.accent, borderRadius: 10, paddingVertical: 3, paddingHorizontal: 9, marginRight: 5, marginBottom: 4 }}>{p}</Text>
          ))}
        </View>
      )}

      <View style={{ position: 'absolute', bottom: 22, left: 44, right: 44, flexDirection: 'row', justifyContent: 'space-between', fontSize: 7.5, color: th.muted, letterSpacing: 1 }} fixed>
        <Text>{bookTitle}</Text>
        <Text render={({ pageNumber }) => String(pageNumber)} />
      </View>
    </Page>
  );
}

function BookletDocument({ items, options }: { items: BookletItem[]; options: BookletOptions }) {
  const th = BOOKLET_THEMES[options.theme];
  // Chinese text in an English-settings booklet (a local draft typed in Chinese)
  // needs the Chinese font too, or it prints as blank boxes.
  const hasCjk = items.some(i => CJK_CHAR.test([i.dishName, i.reflection, i.ingredients, i.recipe].join(' ')));
  const f = resolveFonts(options.language === 'en' && hasCjk ? 'zh-Hant' : options.language);
  const s = buildStyles(th, f);
  const { copy } = options;
  const withPhoto = items.filter(i => i.photoSrc);
  // The featured dish gets the cover's big photo; the rest feed the thumbnails.
  const heroItem = withPhoto.find(i => i.id === options.featuredId) || withPhoto[0];
  const showOthers = (options.coverStyle || 'featured') === 'featured';
  const alsoInside = showOthers ? withPhoto.filter(i => i !== heroItem).slice(0, 3) : [];
  const titleSize = options.title.length > 26 ? 34 : options.title.length > 16 ? 44 : 56;
  const pad = (n: number) => String(n).padStart(2, '0');
  const wrap = (text: string, width: number, size: number) => (f.isCjk ? wrapCjk(text, width, size) : text);

  return (
    <Document title={options.title} author="Nouriva">
      {/* Cover */}
      <Page size="A4" style={s.coverPage}>
        <View style={s.coverTop}>
          {options.logoSrc ? <Image src={options.logoSrc} style={s.coverLogo} /> : null}
          <Text style={s.coverIssue}>{issueLine(options.language)}</Text>
          <Text style={[s.coverTitle, { fontSize: titleSize, lineHeight: 1.05 }]}>{wrap(options.title, 500, titleSize)}</Text>
          <Text style={s.coverTagline}>{copy.tagline}</Text>
        </View>
        <View style={s.coverFrame}>
          {heroItem?.photoSrc ? (
            <View style={{ width: '100%', height: '100%' }}>
              <Image src={heroItem.photoSrc} style={{ width: '100%', flexGrow: 1, flexBasis: 0, objectFit: 'cover' }} />
              {alsoInside.length > 0 && (
                <View>
                  {options.alsoInside ? <Text style={s.coverAlsoLabel}>{options.alsoInside}</Text> : null}
                  <View style={s.coverThumbRow}>
                    {alsoInside.map((p, i) => (
                      <View key={p.id} style={[s.coverThumb, i > 0 ? { marginLeft: 6 } : {}]}>
                        <Image src={p.photoSrc!} style={s.coverThumbImg} />
                        <Text style={s.coverThumbName}>{p.dishName}</Text>
                      </View>
                    ))}
                  </View>
                </View>
              )}
            </View>
          ) : (
            <View style={s.coverBlock}>
              <Text style={s.coverBlockLetter}>{(items[0]?.dishName || options.title).trim().charAt(0).toUpperCase()}</Text>
            </View>
          )}
        </View>
        <View style={s.coverBottom}>
          <Text style={s.coverLine}>{(heroItem || items[0])?.dishName}</Text>
          <Text style={s.coverCount}>{copy.recipeCount(items.length)}</Text>
        </View>
      </Page>

      {/* Contents */}
      <Page size="A4" style={s.page}>
        <View style={s.inner}>
          <Text style={s.label}>{options.title}</Text>
          <Text style={s.heading}>{copy.contentsHeading}</Text>
          <View style={s.rule} />
          {options.editorNote && (
            <View style={s.tocRow}>
              <Text style={s.tocNum}>—</Text>
              <Text style={s.tocTitle}>{options.editorNote.title}</Text>
              <Text style={s.tocMeta}>{copy.editorNoteHeading}</Text>
            </View>
          )}
          {items.map((item, i) => (
            <View key={item.id} style={s.tocRow} wrap={false}>
              <Text style={s.tocNum}>{pad(i + 1)}</Text>
              <Text style={s.tocTitle}>{item.dishName || ' '}</Text>
              <Text style={s.tocMeta}>
                {[item.categoryLabel, item.spiritTags[0] && (item.spiritTagLabels[item.spiritTags[0]] || item.spiritTags[0])].filter(Boolean).join(' · ')}
              </Text>
            </View>
          ))}
        </View>
        <View style={s.pageFooter} fixed>
          <Text>{options.title}</Text>
          <Text render={({ pageNumber }) => String(pageNumber)} />
        </View>
      </Page>

      {/* Editor's note */}
      {options.editorNote && (
        <Page size="A4" style={s.page}>
          <View style={s.inner}>
            <Text style={s.label}>{copy.editorNoteHeading}</Text>
            <Text style={s.heading}>{options.editorNote.title}</Text>
            {options.editorNote.body.split('\n\n').map((para, i) => (
              <Text key={i} style={s.noteBody}>{wrap(para, 487, 12.5)}</Text>
            ))}
            {options.editorNote.questions.length > 0 && (
              <View style={s.noteQuestions}>
                <Text style={s.sideHeading}>{copy.questionsHeading}</Text>
                {options.editorNote.questions.map((q, i) => (
                  <Text key={i} style={s.noteQuestion}>{wrap(q, 455, 12)}</Text>
                ))}
              </View>
            )}
          </View>
          <View style={s.pageFooter} fixed>
            <Text>{options.title}</Text>
            <Text render={({ pageNumber }) => String(pageNumber)} />
          </View>
        </Page>
      )}

      {/* One feature per recipe — one page each (two only when it truly cannot fit), layout alternates for rhythm */}
      {items.map((item, idx) => {
        if (options.layoutStyle === 'playful') {
          return <PlayfulRecipe key={item.id} item={item} idx={idx} th={th} f={f} copy={copy} bookTitle={options.title} wrap={wrap} />;
        }
        const steps = item.recipe ? toSteps(item.recipe) : [];
        const ingredients = item.ingredients ? toIngredients(item.ingredients) : [];
        const tags = item.spiritTags.map(tag => item.spiritTagLabels[tag] || tag).join(' · ');
        const nutrition = nutritionParts(item.nutrition, copy.nutritionLabels).join('   ·   ');
        const plan = planRecipe(item, idx % 2 === 1, f.isCjk, nutrition ? 1 : 0);
        const { k, heroH, layout, twoPage, alt } = plan;
        const rs = buildStyles(th, f, k);
        const hero = item.photoSrc
          ? <Image src={item.photoSrc} style={[rs.heroImage, { height: heroH }]} />
          : (
            <View style={[rs.heroBlock, { height: Math.min(heroH, 200) }]}>
              <Text style={[rs.heroLetter, { fontSize: Math.min(110, Math.max(40, heroH * 0.5)) }]}>
                {(item.dishName || '·').trim().charAt(0).toUpperCase()}
              </Text>
            </View>
          );
        const titleBlock = (
          <View>
            <View style={rs.kicker}>
              <Text style={rs.label}>{[pad(idx + 1), item.categoryLabel].filter(Boolean).join('  ·  ')}</Text>
            </View>
            <Text style={rs.recipeTitle}>{wrap(item.dishName || ' ', 487, 34 * k)}</Text>
            {tags ? <Text style={rs.meta}>{tags}</Text> : null}
          </View>
        );
        const methodBlock = (width: number) => (
          <View>
            <Text style={rs.sideHeading}>{copy.recipeHeading}</Text>
            {steps.map((line, i) => (
              <View key={i} style={rs.stepRow} wrap={false}>
                <Text style={rs.stepNum}>{i + 1}</Text>
                <Text style={rs.stepText}>{wrap(line, width, 11 * k)}</Text>
              </View>
            ))}
          </View>
        );
        const nutritionBlock = nutrition ? (
          <View style={rs.nutrition}>
            <Text style={rs.nutritionLabel}>{copy.nutritionHeading}</Text>
            <Text style={rs.nutritionLine}>{nutrition}</Text>
          </View>
        ) : null;
        const wideCols = layout === 'wide' && ingredients.length > 0 ? splitColumns(ingredients, 222, k, f.isCjk) : null;
        const body = (
          <View>
            {item.reflection ? <Text style={rs.pullQuote}>{wrap(item.reflection, 468, 15 * k)}</Text> : null}
            {layout === 'sidebar' && (ingredients.length > 0 || steps.length > 0) && (
              <View style={rs.columns}>
                {ingredients.length > 0 && (
                  <View style={rs.sidebar}>
                    <Text style={rs.sideHeading}>{copy.ingredientsHeading}</Text>
                    {ingredients.map((line, i) => (
                      <Text key={i} style={rs.ingredient}>{wrap(line, 147, 10.5 * k)}</Text>
                    ))}
                  </View>
                )}
                {steps.length > 0 && <View style={rs.main}>{methodBlock(268)}</View>}
              </View>
            )}
            {layout === 'wide' && (
              <View style={{ marginTop: 20 }}>
                {wideCols && (
                  <View style={[rs.sidebar, { width: '100%', marginRight: 0 }]}>
                    <Text style={rs.sideHeading}>{copy.ingredientsHeading}</Text>
                    <View style={{ flexDirection: 'row' }}>
                      {wideCols.map((col, ci) => (
                        <View key={ci} style={{ width: '50%', paddingRight: ci === 0 ? 7 : 0, paddingLeft: ci === 1 ? 7 : 0 }}>
                          {col.map((line, i) => (
                            <Text key={i} style={rs.ingredient}>{wrap(line, 222, 10.5 * k)}</Text>
                          ))}
                        </View>
                      ))}
                    </View>
                  </View>
                )}
                {!twoPage && steps.length > 0 && <View style={{ marginTop: wideCols ? 14 : 0 }}>{methodBlock(463)}</View>}
              </View>
            )}
            {!twoPage && nutritionBlock}
          </View>
        );

        const footer = (
          <View style={s.pageFooter} fixed>
            <Text>{options.title}</Text>
            <Text render={({ pageNumber }) => String(pageNumber)} />
          </View>
        );

        return (
          <Fragment key={item.id}>
            <Page size="A4" style={s.page}>
              {!alt ? (
                <View>
                  {hero}
                  <View style={{ paddingHorizontal: 54, paddingTop: 22 }}>
                    {titleBlock}
                    {body}
                  </View>
                </View>
              ) : (
                <View>
                  <View style={{ paddingHorizontal: 54, paddingTop: 46 }}>{titleBlock}</View>
                  <View style={{ marginTop: 18, marginHorizontal: 54 }}>{hero}</View>
                  <View style={{ paddingHorizontal: 54 }}>{body}</View>
                </View>
              )}
              {footer}
            </Page>
            {twoPage && (
              <Page size="A4" style={s.page}>
                <View style={s.inner}>
                  <Text style={s.label}>{[pad(idx + 1), item.categoryLabel].filter(Boolean).join('  ·  ')}</Text>
                  <Text style={[s.heading, { fontSize: 26, marginBottom: 14 }]}>{wrap(item.dishName || ' ', 487, 26)}</Text>
                  <View style={s.rule} />
                  <View style={{ marginTop: 14 }}>{methodBlock(463)}</View>
                  {nutritionBlock}
                </View>
                {footer}
              </Page>
            )}
          </Fragment>
        );
      })}

      {/* Back cover */}
      <Page size="A4" style={s.backPage}>
        {options.logoSrc ? <Image src={options.logoSrc} style={s.backLogo} /> : null}
        {options.dedication ? <Text style={s.dedication}>{wrap(options.dedication, 455, 20)}</Text> : null}
        {options.dedication ? <View style={s.backRule} /> : null}
        <Text style={s.backMark}>{copy.madeWith}</Text>
        {options.appUrl ? (
          <Link src={options.appUrl} style={s.backLink}>{options.appUrl.replace(/^https?:\/\//, '')}</Link>
        ) : null}
      </Page>
    </Document>
  );
}

export async function generateBookletPdf(items: BookletItem[], options: BookletOptions): Promise<Blob> {
  return pdf(<BookletDocument items={items} options={options} />).toBlob();
}

// Exposed for the Node-side render check (scripts / tests), which needs a
// Buffer instead of a browser Blob.
export { BookletDocument, planPlayful };
